import type { Project } from '../../../core/types/project.ts'

const projects = [
  {
    title: 'Velia',
    type: 'Side project · In development',
    from: null,
    to: null,
    desc: 'A personal project in development combining hexagonal architecture and applied AI across web and mobile.<br /><br />A Go backend with React, TypeScript and React Native interfaces. LLM integration with tool calling and MCP, response evaluation, and cost and latency observability.',
    techs: ['go', 'react', 'ts', 'postgre'],
    link: null,
  },
  {
    title: 'Personal website <bnarvaez.dev>',
    type: 'Open Source',
    from: 'JUN 2022',
    to: null,
    desc: 'The website you are viewing: Vue 3, TypeScript and Sass, with Vite and Vitest. Separate core and UI layers, typed translations, static pages in Spanish and English, and Biome for formatting and code quality.',
    techs: ['vue', 'ts', 'js', 'sass', 'vite', 'vitest', 'figma'],
    link: 'https://github.com/prinick96/bnarvaez.dev',
  },
  {
    title: 'Hexagonal Architecture in Go',
    type: 'Open Source',
    from: 'JUN 2022',
    to: null,
    desc: 'A ToDo application with hexagonal architecture in Go, including use case examples and tests, ready to deploy with Docker and Heroku.<br /><br />You can use it as a template for your own projects.',
    techs: ['docker', 'heroku', 'go'],
    link: 'https://github.com/prinick96/hex-arch-go',
  },
  {
    title: 'Didoc for Doctors and Medical Centers',
    type: 'Customer',
    from: 'MAR 2021',
    to: null,
    desc: 'A platform for online appointment booking, video consultations, patient and role management, payments and verified electronic prescriptions.<br /><br />The backend uses microservices and a Backend for Frontend architecture with Go, Python and Node.js. Each microservice follows hexagonal architecture and connects to CockroachDB, MongoDB and RabbitMQ.<br /><br />Several frontend applications consume these services. Most, including the main interface, use Vue; the video consultation interface uses React.',
    techs: ['go', 'python', 'next', 'cockroach', 'mongodb', 'rabbit', 'vue', 'sass', 'ts', 'vite'],
    link: null,
  },
  {
    title: 'Bilance BTC and USDT wallet in Go',
    type: 'Customer',
    from: 'JUL 2021',
    to: 'FEB 2022',
    desc: 'A platform that works as a wallet for BTC and USDT and micro exchange, to be able to make exchanges between the two currencies, the platform always kept a percentage of profit between each exchange and the users had a great referral system that rewarded with actions of the referrals within the platform <br /><br />The Fronted written in Vue 2 The Backend written in Go, with a Model-Controller structure',
    techs: ['go', 'node', 'cpp', 'vue', 'sass', 'html5', 'js', 'ts'],
    link: null,
  },
  {
    title: '7Trading',
    type: 'Customer',
    from: 'MAY 2021',
    to: 'JUN 2021',
    desc: 'Cryptocurrency investment signal delivery platform, written the backend in Go and the front in Vue The creators of the signals made a graph in TradingView with the estimate of price rise/fall and from a backoffice they created the signal, which was notified by Telegram with a bot, the users opened the signal and saw the prediction graph to proceed to make the investment',
    techs: ['go', 'node', 'vue', 'sass', 'html5'],
    link: null,
  },
  {
    title: 'THD cryptocurrency and decentralized platform',
    type: 'Customer',
    from: 'NOV 2018',
    to: 'JUL 2019',
    desc: "Customer A currency project that started as a FORK of Dash to build a cryptocurrency called THD that would focus on a decentralized platform and its value would grow based on the usability of the platform.\n            <br /><br />Being a dash fork, the cryptocurrency could be mined and deploy masternodes, which are basically super nodes that reserve X amounts of the cryptocurrency to work.\n            <br /><br />The aforementioned platform has developed all the functionality of interaction with the cryptocurrency, I made a service in Node.js which communicated with the gensis node and managed the wallets and their content, \n            this was represented graphically in the client's dashboard , written in Vue In addition, automated masternodes could be deployed, which were charged to clients with Bitcoin or with the THD cryptocurrency.\n            <br /><br />These masternodes were Droplets from Digital Ocean that replicated the main node and worked as a masternode for the client's wallet, so I had to interact with the Digital Ocean api and install a Go script in the deployment \n            that replicated the node and left the masternode configured.\n            <br /><br />It is one of the most interesting projects that I have had the opportunity to do, unfortunately the project is not up and running, however I keep all the code in my private repositories to show how it works.",
    techs: ['go', 'php', 'node', 'dash', 'cpp', 'linux', 'vue', 'js', 'sass', 'html5'],
    link: null,
  },
  {
    title: 'NEM wallet API',
    type: 'Customer',
    from: 'NOV 2018',
    to: 'DEC 2018',
    desc: 'An API written in Java to interact with a NEM cryptocurrency node.',
    techs: ['java', 'nem'],
    link: null,
  },
  {
    title: 'Ocrend PHP Framework',
    type: 'Open Source',
    from: 'MAR 2017',
    to: 'OCT 2018',
    desc: 'Ocrend was the name of a small academy that wanted to do on Youtube, and I focused on creating a small PHP Framework focused on MVC, the idea was to learn to program a web system using a MVC architecture and learn in the procces.',
    techs: ['php', 'mysql', 'postgre'],
    link: 'https://github.com/prinick96/Ocrend-Framework',
  },
  {
    title: 'Bitmarket: interactive shopping cart in JS and PHP',
    type: 'Customer',
    from: 'FEB 2018',
    to: 'APR 2018',
    desc: 'Customer A quite fun project that consisted of having a shopping cart and moving it down an aisle and taking the products to buy from the shelves, the project was not finished but I still have the repository to show it working \n            <br /><br />The cart and the other components were .svg snippets that I controlled with css animations. It also had music. The form of payment at the end of the product selection was with an ERC20 Token made for the client and also Bitcoin.',
    techs: ['php', 'css3', 'html5', 'js', 'node'],
    link: null,
  },
  {
    title: 'E-commerce as a service',
    type: 'Customer',
    from: 'FEB 2017',
    to: 'JAN 2018',
    desc: "Customer JAN 2018 It was the first project I worked the backend as a service and I stopped making a monolith between fronted and backend\n            .<br /><br />I worked on the front with Coffescript, without using external libraries.\n            <br /><br />The backend was made in PHP with Symfony's Silex for the API.\n            <br /><br />I did the design of the interfaces myself with Adobe Photoshop A small ecommerce with the specific needs of the client",
    techs: ['php', 'symfony', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Voting system for Paraguay',
    type: 'Customer',
    from: 'NOV 2017',
    to: null,
    desc: 'Customer Written with a own PHP framework, I made a simple system for voting candidates in a one-page interface\n            <br /><br />The candidates were uploaded manually and then appeared on the main page to vote The voting had an opening and closing schedule according to the local time in Paraguay.\n            <br /><br />Frontend made with Javascript and jQuery to consume the backend api.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Management software for phone repair technicians',
    type: 'Customer',
    from: 'SEP 2017',
    to: 'OCT 2017',
    desc: 'Customer Dashboard written in PHP that allowed a control in the flow of work and inventory of a small company of cell phone technicians.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Personal website with the YouTube API',
    type: 'Open Source',
    from: 'OCT 2017',
    to: null,
    desc: 'I wrote the project in a self PHP framework. It connects with the YouTube API and shows my most recently uploaded videos <br /><br />It was a personal website to complement my Youtube channel.',
    techs: ['php', 'js', 'html5', 'css3'],
    link: 'https://github.com/prinick96/prinick.com/',
  },
  {
    title: 'BTC to CLP/BS/USD calculator',
    type: 'Customer',
    from: 'OCT 2017',
    to: null,
    desc: 'Customer A small frontend app that consumed from multiples APIS, including coinmarketcap to calculate the current price of Bitcoin in the selected local currency.',
    techs: ['js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Vehicle maintenance tracking',
    type: 'Customer',
    from: 'MAR 2017',
    to: 'JUN 2017',
    desc: "A web system written in PHP with Codeigniter, to manage everything about trailers, utility vehicles or tractor heads. \n            <br /><br /> All of these had a series of fields to describe services to be performed, each vehicle had a history of driver assignments.\n            <br /><br /> Each driver had to be able to drive a maximum of one tractor or utility vehicle and one trailer. Each vehicle had a number of axles on which a defined number of tires were assigned, replaced either at the vehicle's location or moved to another vehicle, so there was a history of those modifications.\n            <br /><br /> The dashboard was notified when a vehicle already needed another review, which was scheduled based on the mileage of each one. Each driver had his own user to manage everything related to him.",
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Assembly partition simulator',
    type: 'Open Source',
    from: 'JUN 2017',
    to: null,
    desc: 'Research project that simulates block movement and cache partitioning using the FIFO replacement algorithm. Made in ASM for Win32 with a command line interface. <br /><br />Written in one night.',
    techs: ['asm', 'csharp'],
    link: 'https://github.com/prinick96/cache-asm/blob/master/main.asm',
  },
  {
    title: 'Linux Processes and Threads',
    type: 'Open Source',
    from: 'MAY 2017',
    to: null,
    desc: 'Research project to become familiar with system calls related to creating and managing processes and threads using the POSIX library for creating processes and threads in Linux using C with a command interface.',
    techs: ['cpp', 'linux'],
    link: 'https://github.com/prinick96/procesos_e_hilos_SO',
  },
  {
    title: 'Real Estate Directory',
    type: 'Customer',
    from: 'OCT 2016',
    to: 'FEB 2017',
    desc: 'Project for a real estate agency in Mexico written in PHP with Laravel, HTML, CSS and JS It was a web directory where the real estate agency could place all its properties for rent and sale through a backoffice\n            <br /><br />The publications had photos and a 3D viewer on some occasions, with a contact form to be able to schedule appointments.\n            <br /><br />The backoffice had several administrator users with defined roles, including real estate agents who managed the assigned properties I worked with a graphic designer to make the directory interfaces.',
    techs: ['php', 'laravel', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Video website',
    type: 'Customer',
    from: 'AUG 2016',
    to: 'DEC 2016',
    desc: 'Project developed for a client in Puerto Rico who wanted to have a website to display videos The project is written in PHP and I make use of the FFMpeg library for PHP, which was installed as a library in linux to handle media\n            <br /><br />I used it to extract thumbs from the videos and they will be previewed when hovering over them. \n            <br /><br />Before the project, the client had a wordpress with almost 10TB of videos, so I also had to program a tool that would migrate all that information to the new database, including moving the files from one server to another. \n            <br /><br />The site had to be multilanguage, have a user system, video classification, comments, downloads allowed for premium users, paypal payment gateway for premium subscription.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3', 'linux'],
    link: null,
  },
  {
    title: 'Low-level cache simulator',
    type: 'Open Source',
    from: 'NOV 2016',
    to: 'DEC 2016',
    desc: 'Research project to simulate the behavior of a memory hierarchy consisting of a cache memory and a main memory\n            <br /><br />Direct mapping to a number.\n            <br /><br />Set-associative mapping to a number.\n            <br /><br />Movement of blocks in the cache.\n            <br /><br />Cache replacement algorithms (LRU, FIFO, RAND).',
    techs: ['c'],
    link: 'https://github.com/prinick96/cache-simulator',
  },
  {
    title: 'Semester course registration',
    type: 'Open Source',
    from: 'JUN 2016',
    to: 'JUL 2016',
    desc: 'Research project for the university written in C++ using dynamic memory, with a command interface. \n            <br /><br />The information was saved in .txt files to later retrieve them when the program was started again It consists of a complete curriculum with the respective subjects for each semester, each subject with its teacher availability and hours.\n            <br /><br />The program had to successfully enter all the students in the selected subjects, if a subject ran out of space, it had to relocate the student who needed it in another available schedule/section taking into account the subjects already registered in their own schedule',
    techs: ['cpp'],
    link: 'https://github.com/prinick96/program_ii',
  },
  {
    title: 'MLM with PayPal Marketplace',
    type: 'Open Source',
    from: 'ABR 2015',
    to: 'FEB 2016',
    desc: 'It was my first long-term project, it consisted of a multilevel binary network where payments were made via Paypal, each user had an associated Paypal account where they would receive the money, when a child user made a payment, the money was distributed in the form of commissions among all those listed above it and the money was automatically deposited.',
    techs: ['php', 'mysql', 'js', 'css3', 'html5'],
    link: 'https://github.com/prinick96/program_ii',
  },
  {
    title: 'Xnova Revolution',
    type: 'Open Source',
    from: 'FEB 2010',
    to: 'MAR 2011',
    desc: "Basically it was 2010, I was around 14 years old and I was playing OGame, a military strategy game in space, so I thought about creating my own OGame server\n            <br /><br />What did I have to do? I only knew HTML, CSS and JS, so I learned PHP and I developed my own OGame clone.\n            <br /><br />The project started open source and had the collaboration of many more people, at that time I didn't even know what git was, so I always used SVN for version control of the project and the entire code is on SourceForge.\n            <br /><br />If you download it, you will see my name in the credits of the core of the project and also in any game server that is currently running (even if the credits are removed), such as http://www.xnovarevolution.net in the changelog I made all the interface design with Photoshop, I did the layout and core programming",
    techs: ['php', 'mysql', 'html5', 'css3', 'js', 'photoshop'],
    link: 'https://sourceforge.net/projects/xnovarevolution/',
  },
] satisfies readonly Project[]

export default projects
