import type { Project } from '../../../core/types/project.ts'

const projects = [
  {
    title: 'Velia',
    type: 'Side project · En desarrollo',
    from: null,
    to: null,
    desc: 'Proyecto personal en desarrollo que combina arquitectura hexagonal e IA aplicada en web y móvil.<br /><br />Backend en Go e interfaces con React, TypeScript y React Native. Integración de LLMs con tool calling y MCP, evaluación de respuestas y observabilidad de costes y latencia.',
    techs: ['go', 'react', 'ts', 'postgre'],
    link: null,
  },
  {
    title: 'Web personal <bnarvaez.dev>',
    type: 'Open Source',
    from: 'JUN 2022',
    to: null,
    desc: 'La web que estás viendo: Vue 3, TypeScript y Sass, con Vite y Vitest. Arquitectura separada en core y UI, traducciones tipadas, páginas estáticas en español e inglés y Biome para formato y calidad de código.',
    techs: ['vue', 'ts', 'js', 'sass', 'vite', 'vitest', 'figma'],
    link: 'https://github.com/prinick96/bnarvaez.dev',
  },
  {
    title: 'Arquitectura Hexagonal escrita en Go',
    type: 'Open Source',
    from: 'JUN 2022',
    to: null,
    desc: 'Un sistema ToDo con Arquitectura Hexagonal escrito en Go, ejemplos de casos de uso y cómo testearlos, listo para desplegar con Docker y Heroku.<br /><br />Puedes utilizarlo como template para tus propios proyectos.',
    techs: ['docker', 'heroku', 'go'],
    link: 'https://github.com/prinick96/hex-arch-go',
  },
  {
    title: 'Didoc para Centros Médicos y Doctores',
    type: 'Cliente',
    from: 'MAR 2021',
    to: null,
    desc: 'Una plataforma para agendamiento de citas online, teleconsultas, gestión de pacientes, administración de roles, cobros, receta electrónica verificada,  etc.<br /><br /> El backend son varios microservicios que están montados con la arquitectura Backend For Frontend escritos en Go, Python y Node, cada microservicio está realizado utilizando arquitectura hexagonal, conexión con CockroachDB, MongoDB y RabbitMQ.<br /><br /> Hay varios frontend que consumen los microservicios, casi todos incluyendo el principal están escritos en VueJs y la teleconsulta utiliza ReactJs.',
    techs: ['go', 'python', 'next', 'cockroach', 'mongodb', 'rabbit', 'vue', 'sass', 'ts', 'vite'],
    link: null,
  },
  {
    title: 'Bilance wallet de BTC y USDT en Go',
    type: 'Cliente',
    from: 'JUL 2021',
    to: 'FEB 2022',
    desc: 'Una plataforma que funcionaba como monedero para BTC y USDT y micro exchange, para poder hacer intercambios entre las dos monedas, la plataforma se quedaba siempre con un porcentaje de ganancia entre cada intercambio y los usuarios tenían un gran sistema de referidos que bonificaba con acciones de los referidos dentro de la plataforma.<br /><br /> El Frontend escrito en Vue 2<br /> El Backend escrito en GO, con una estructura de Model-Controller.',
    techs: ['go', 'node', 'cpp', 'vue', 'sass', 'html5', 'js', 'ts'],
    link: null,
  },
  {
    title: '7Trading',
    type: 'Cliente',
    from: 'MAY 2021',
    to: 'JUN 2021',
    desc: 'Plataforma de envío de señales de inversión de criptomonedas, escrito el backend en Go y el front en Vue.<br /><br />Los creadores de las señales hacían una gráfica en TradingView con la estimación de subida/caída del precio y desde un backoffice creaban la señal, la cual era notificada por Telegram con un bot, los usuarios abrían la señal y veían la gráfica de predicción para proceder a realizar la inversión.',
    techs: ['go', 'node', 'vue', 'sass', 'html5'],
    link: null,
  },
  {
    title: 'THD Criptomoneda y plataforma descentralizada',
    type: 'Cliente',
    from: 'NOV 2018',
    to: 'JUL 2019',
    desc: 'Un proyecto de moneda que empezó como un FORK de Dash para levantar una criptomoneda llamada THD que se centrara en una plataforma descentralizada y su valor creciera en función de la usabilidad de la plataforma.<br /><br />Al ser un fork de dash, la criptomoneda se podía minar y desplegar masternodos, que básicamente son super nodos que reservan cantidades X de la criptomoneda para funcionar.<br /><br />La plataforma en cuestión, tiene desarrollada toda la funcionalidad de interacción con la criptomoneda, hice un servicio en Node.js que se comunicaba con el nodo gensis y gestionaba los monederos y su contenido, esto se representaba de forma gráfica en el dashboard de los clientes, escrito en Vue.<br /><br /> Además, se podía desplegar masternodos automatizados, los cuales se cobraban a los clientes con Bitcoin o con la criptomoneda THD.<br /><br />Estos masternodos eran Droplets de Digital Ocean que replicaban el nodo principal y funcionaban como un masternodo de la wallet del cliente, por lo que tuve que interactuar con la api de Digital Ocean e instalar en el despliegue, un script en Go que realizaba la réplica del nodo y dejaba configurado el masternodo.<br /><br />Es uno de los proyectos más interesantes que he tenido oportunidad de hacer, desafortunadamente el proyecto no está en pie, sin embargo conservo todo el código en mis repositorios privados para mostrar el funcionamiento.',
    techs: ['go', 'php', 'node', 'dash', 'cpp', 'linux', 'vue', 'js', 'sass', 'html5'],
    link: null,
  },
  {
    title: 'NEM Crypto api para wallet',
    type: 'Cliente',
    from: 'NOV 2018',
    to: 'DIC 2018',
    desc: 'API para interactuar con un nodo de la criptomoneda NEM, escrito en Java',
    techs: ['java', 'nem'],
    link: null,
  },
  {
    title: 'Ocrend PHP Framework',
    type: 'Open Source',
    from: 'MAR 2017',
    to: 'OCT 2018',
    desc: 'Ocrend era el nombre de una pequeña academia que quise hacer en YouTube, y me enfoqué en crear un pequeño Framework de PHP enfocado en MVC, la idea era aprender a programar un sistema web utilizando la arquitectura MVC y aprender en el proceso.',
    techs: ['php', 'mysql', 'postgre'],
    link: 'https://github.com/prinick96/Ocrend-Framework',
  },
  {
    title: 'Bitmarket carrito de compras tipo video juego en JS y PHP',
    type: 'Cliente',
    from: 'FEB 2018',
    to: 'APR 2018',
    desc: 'Un proyecto bastante divertido que consistía en tener un carrito de compras e irlo moviendo por un pasillo y tomar los productos a comprar de los anaqueles, el proyecto no se terminó pero aún conservo el repositorio para mostrarlo funcionando.<br /><br />El carrito y los demás componentes eran snippets en .svg que controlaba con animaciones css. Además tenía música.<br /><br />La forma de pago al finalizar la selección de productos era con un Token ERC20 realizado para el cliente y también Bitcoin.',
    techs: ['php', 'css3', 'html5', 'js', 'node'],
    link: null,
  },
  {
    title: 'Ecommerce como servicio',
    type: 'Cliente',
    from: 'FEB 2017',
    to: 'ENE 2018',
    desc: 'Fue el primer proyecto en el que trabajé el backend como servicio y dejé de hacer un monolito entre frontend y backend.<br /><br />El front lo trabajé con Coffescript, sin uso de librerías externas.<br /><br />El backend fue hecho en PHP con Silex de Symfony para la API.<br /><br />El diseño de las interfaces lo hice yo mismo con Adobe Photoshop.<br /><br />Un ecommerce pequeño con las necesidades concretas del cliente.',
    techs: ['php', 'symfony', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Sistema de votos Paraguay',
    type: 'Cliente',
    from: 'NOV 2017',
    to: null,
    desc: 'Escrito con un framework PHP propio, hice un sistema sencillo para hacer votaciones de candidatos en una interfaz de una página.<br /><br />Los candidatos se cargaban manualmente y luego aparecían en la página principal para hacer las votaciones.<br /><br />Las votaciones tenían un horario de apertura y cierre según la hora local de Paraguay.<br /><br />Frontend hecho con Javascript y jQuery para consumir la api del backend.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Software de control para técnicos de teléfonos',
    type: 'Cliente',
    from: 'SEP 2017',
    to: 'OCT 2017',
    desc: 'Dashboard escrito en PHP que permitía un control en el flujo de trabajo e inventario de una pequeña empresa de técnicos de teléfonos celulares.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Página personal con API de Youtube',
    type: 'Open Source',
    from: 'OCT 2017',
    to: null,
    desc: 'El proyecto lo escribí en un framework propio de PHP. Se conecta con la API de YouTube y mostraba mis videos más recientes subidos.<br /><br />Era un sitio web personal para acompañar a mi canal de YouTube.',
    techs: ['php', 'js', 'html5', 'css3'],
    link: 'https://github.com/prinick96/prinick.com/',
  },
  {
    title: 'Calculadora de BTC a CLP/BS/USD',
    type: 'Cliente',
    from: 'OCT 2017',
    to: null,
    desc: 'Una pequeña app frontend que consumía de varias APIS, entre ellas de coinmarketcap para hacer un cálculo del precio de Bitcoin del momento a la moneda local seleccionada.',
    techs: ['js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Tracking para mecánica de vehículos',
    type: 'Cliente',
    from: 'MAR 2017',
    to: 'JUN 2017',
    desc: 'Un sistema web escrito en PHP con Codeigniter, para gestionar todo acerca de remolques, utilitarios de vehículos o cabezas tractoras. Todos estos tenían una serie de campos para describir servicios a realizar, cada vehículo tenía un historial de asignaciones de conductores. Cada conductor debía poder manejar máximo una tractora o utilitaria y un remolque. Cada vehículo tenía una cantidad de ejes en los cuales se les asigna una cantidad definida de neumáticos, eran sustituidos o reemplazados tanto en la ubicación del vehículo o movidos a otro vehículo, por tanto había un historial de esas modificaciones. En el dashboard se notificaba cuando algún vehículo ya necesitaba otra revisión, la cual era programada en base al Km de cada uno. Cada conductor tenía su propio usuario para gestionar todo lo relacionado con él.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Simulador de particionamiento en ASSEMBLY',
    type: 'Open Source',
    from: 'JUN 2017',
    to: null,
    desc: 'Proyecto de investigación que simula el movimiento de bloques y particionamiento en memoria caché utilizando el algoritmo de reemplazo FIFO. Realizado en ASM para Win32 con una interfaz de comandos.<br /><br />Escrito en una noche.',
    techs: ['asm', 'csharp'],
    link: 'https://github.com/prinick96/cache-asm/blob/master/main.asm',
  },
  {
    title: 'Procesos e Hilos de Linux',
    type: 'Open Source',
    from: 'MAY 2017',
    to: null,
    desc: 'Proyecto de investigación para familiarizarse con los llamados al sistema relativos a la creación y administración de procesos e hilos usando la librería POSIX para la creación de procesos e hilos en Linux usando C con interfaz de comandos.',
    techs: ['cpp', 'linux'],
    link: 'https://github.com/prinick96/procesos_e_hilos_SO',
  },
  {
    title: 'Directorio para Inmobiliaria',
    type: 'Cliente',
    from: 'OCT 2016',
    to: 'FEB 2017',
    desc: 'Proyecto para una inmobiliaria en México escrito en PHP con Laravel, HTML, CSS y JS.<br /><br />Era un directorio web donde la inmobiliaria podía colocar a través de un backoffice todas sus propiedades en arriendo y venta.<br /><br />Las publicaciones tenían fotos y un visor 3D en algunas ocasiones, con un formulario de contacto para poder agendar citas.<br /><br />El backoffice tenía varios usuarios administradores con roles definidos, entre ellos, los agentes de inmueble que gestionaban las propiedades asignadas.<br /><br />Trabajé con un diseñador gráfico para realizar las interfaces del directorio.',
    techs: ['php', 'laravel', 'mysql', 'js', 'html5', 'css3'],
    link: null,
  },
  {
    title: 'Web de videos',
    type: 'Cliente',
    from: 'AUG 2016',
    to: 'DIC 2016',
    desc: 'Proyecto desarrollado para un cliente en puerto rico que deseaba tener un sitio web para mostrar videos.<br /><br />El proyecto está escrito en PHP y hago uso de la librería FFMpeg para PHP, la cual se instalaba como una librería en linux para poder manejar medios, la utilicé para extraer thumbs de los videos y éstos se previsualizaran al pasar el mouse por encima.<br /><br />Antes del proyecto, el cliente tenía un wordpress con casi 10TB de videos, por lo que también tuve que programar una herramienta que migrara toda esa información a la nueva base de datos, incluyendo mover los archivos de un servidor a otro.<br /><br />El sitio debía ser multilenguaje, tener un sistema de usuarios, clasificación de videos, comentarios, descargas permitidas para usuarios premium, pasarela de pago en paypal para la suscripción premium.',
    techs: ['php', 'mysql', 'js', 'html5', 'css3', 'linux'],
    link: null,
  },
  {
    title: 'Simulador de Caché a bajo nivel',
    type: 'Open Source',
    from: 'NOV 2016',
    to: 'DIC 2016',
    desc: 'Proyecto de investigación para simular el comportamiento de una jerarquía de memoria que consiste en una memoria caché y una memoria principal.<br /><br />Mapeo directo hacia un número.<br /><br />Mapeo asociativo por conjunto hacia un número.<br /><br />Movimiento de bloques en la memoria caché.<br /><br />Algoritmos de reemplazo en caché (LRU, FIFO, RAND).',
    techs: ['c'],
    link: 'https://github.com/prinick96/cache-simulator',
  },
  {
    title: 'Inscripción de materias del semestre, para alumnos',
    type: 'Open Source',
    from: 'JUN 2016',
    to: 'JUL 2016',
    desc: 'Proyecto de investigación para la univesidad escrito en C++ usando memoria dinámica, con interfaz de comandos. La información se guardaba en archivos .txt para posteriormente recuperarlas al volver a iniciar el programa.<br /><br />Consiste en un pensum completo con las respectivas materias de cada semestre, cada materia con su disponibilidad de profesor y horas.<br /><br />El programa debía ingresar con éxito todos los alumnos en las materias seleccionadas, si una materia se quedaba sin cupo, debía reubicar al alumno que la necesitaba en otro horario/sección disponible teniendo en cuenta las materias ya inscritas en su propio horario.',
    techs: ['cpp'],
    link: 'https://github.com/prinick96/program_ii',
  },
  {
    title: 'Multinivel con Paypal Marketplace',
    type: 'Open Source',
    from: 'ABR 2015',
    to: 'FEB 2016',
    desc: 'Fue mi primer proyecto de larga duración, consistía en una red binaria multinivel donde se realizaban cobros vía Paypal, cada usuario tenía una cuenta de Paypal asociada donde recibiría el dinero, cuando un usuario hijo hacía un pago, se distribuía el dinero en forma de comisiones entre todos los relacionados arriba del mismo y se depositaba automáticamente el dinero.',
    techs: ['php', 'mysql', 'js', 'css3', 'html5'],
    link: 'https://github.com/prinick96/program_ii',
  },
  {
    title: 'Xnova Revolution',
    type: 'Open Source',
    from: 'FEB 2010',
    to: 'MAR 2011',
    desc: 'Básicamente era 2010, tenía al rededor de 14 años y jugaba OGame, un juego de estrategia militar en el espacio, entonces pensé en crear mi propio servidor de OGame.<br /><br />¿Qué tenía que hacer? Sólo sabía HTML, CSS y JS, entonces aprendí PHP y desarrollé mi propio clon de OGame.<br /><br />El proyecto empezó open source y tuvo colaboración de muchas más personas, en ese momento ni sabía lo que era git, por lo que siempre usaba SVN para el control de versiones del proyecto y el código entero está en SourceForge.<br /><br />Si lo descargas, verás mi nombre en los créditos del core del proyecto y también en cualquier servidor del juego que esté funcionando actualmente (aunque le retiren los créditos), como por ejemplo http://www.xnovarevolution.net en el changelog.<br /><br />Todo el diseño de la interfaz lo hice yo con Photoshop, hice la maquetación y la programación del core.',
    techs: ['php', 'mysql', 'html5', 'css3', 'js', 'photoshop'],
    link: 'https://sourceforge.net/projects/xnovarevolution/',
  },
] satisfies readonly Project[]

export default projects
